/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkg00030a;

/**
 *
 * @author anjali
 */
public class employee extends javax.swing.JFrame {

    /**
     * Creates new form employee
     */
    public employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        emsystem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        emstaff = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        emlogin = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        eminsert = new javax.swing.JButton();
        emlogintime = new javax.swing.JTextField();
        emupdate = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        emdelete = new javax.swing.JButton();
        emsearch = new javax.swing.JButton();
        emid = new javax.swing.JTextField();
        empssword = new javax.swing.JTextField();
        emname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        emfname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        emlaname = new javax.swing.JTextField();
        ememail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        emdatejoined = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        emmobilenum = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel9.setText("Syatem activity");

        emsystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emsystemActionPerformed(evt);
            }
        });

        jLabel10.setText("Staff member");

        emstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emstaffActionPerformed(evt);
            }
        });

        jLabel11.setText("Login date");

        jLabel12.setText("Login time");

        jLabel6.setText("E-mail");

        emlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emloginActionPerformed(evt);
            }
        });

        jLabel13.setText("Last name");

        jLabel7.setText("Data joined");

        eminsert.setText("INSERT");
        eminsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eminsertActionPerformed(evt);
            }
        });

        emupdate.setText("UPDATE");
        emupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emupdateActionPerformed(evt);
            }
        });

        jLabel8.setText("Mobile number");

        emdelete.setText("DELETE");
        emdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emdeleteActionPerformed(evt);
            }
        });

        emsearch.setText("SEARCH");
        emsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emsearchActionPerformed(evt);
            }
        });

        emid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emidActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Employee details");

        emfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emfnameActionPerformed(evt);
            }
        });

        jLabel2.setText("Id");

        jLabel3.setText("User password");

        emdatejoined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emdatejoinedActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        jLabel5.setText("Frist name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eminsert)
                        .addGap(18, 18, 18)
                        .addComponent(emupdate)
                        .addGap(28, 28, 28)
                        .addComponent(emdelete)
                        .addGap(27, 27, 27)
                        .addComponent(emsearch))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emid)
                            .addComponent(empssword)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(emname)
                            .addComponent(emfname)
                            .addComponent(emlaname)
                            .addComponent(ememail)
                            .addComponent(emdatejoined)
                            .addComponent(emmobilenum)
                            .addComponent(emsystem)
                            .addComponent(emstaff)
                            .addComponent(emlogin)
                            .addComponent(emlogintime))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(emid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(empssword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(emfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(emlaname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ememail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(emdatejoined, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(emmobilenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(emsystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(emstaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(emlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(emlogintime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eminsert)
                    .addComponent(emupdate)
                    .addComponent(emdelete)
                    .addComponent(emsearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emsystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emsystemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emsystemActionPerformed

    private void emstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emstaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emstaffActionPerformed

    private void emloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emloginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emloginActionPerformed

    private void eminsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eminsertActionPerformed
        // TODO add your handling code here:
        connect ob=new connect ();
        ob.connectdb();

        String  id =emid.getText();
        int ed =Integer.parseInt(id);
        String uspswrd =empssword.getText();
        String name =emname.getText();
        String fname =emfname.getText();
        String lname =emlaname.getText();
        String email =ememail.getText();
        String  join=emdatejoined.getText();
        String  num =emmobilenum.getText();
        int nu =Integer.parseInt(num);
        String system=emsystem.getText();
        String stf = emstaff.getText();
        String date =emlogin.getText();
        String  time =emlogintime.getText();

        ob.insertData(ed, uspswrd, name, fname, lname, email, join, nu, system, stf, date, time);

    }//GEN-LAST:event_eminsertActionPerformed

    private void emupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emupdateActionPerformed
        // TODO add your handling code here:
        connect ob=new connect ();
        ob.connectdb();

         String  id =emid.getText();
        int ed =Integer.parseInt(id);
        
        
        String  num =emmobilenum.getText();
        int nu =Integer.parseInt(num);
        
      ob.updateData(ed, nu);
    }//GEN-LAST:event_emupdateActionPerformed

    private void emdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emdeleteActionPerformed
        // TODO add your handling code here:

        connect ob=new connect ();
        ob.connectdb();

        String  id =emid.getText();
        int ed =Integer.parseInt(id);
        ob.deleteData(ed);
        
    }//GEN-LAST:event_emdeleteActionPerformed

    private void emsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emsearchActionPerformed
        // TODO add your handling code here:
        connect ob=new connect ();
        ob.connectdb();
        String  id =emid.getText();
        int ed=Integer.parseInt(id);
        ob.searchData(ed);
        
    }//GEN-LAST:event_emsearchActionPerformed

    private void emidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emidActionPerformed

    private void emfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emfnameActionPerformed

    private void emdatejoinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emdatejoinedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emdatejoinedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emdatejoined;
    private javax.swing.JButton emdelete;
    private javax.swing.JTextField ememail;
    private javax.swing.JTextField emfname;
    private javax.swing.JTextField emid;
    private javax.swing.JButton eminsert;
    private javax.swing.JTextField emlaname;
    private javax.swing.JTextField emlogin;
    private javax.swing.JTextField emlogintime;
    private javax.swing.JTextField emmobilenum;
    private javax.swing.JTextField emname;
    private javax.swing.JTextField empssword;
    private javax.swing.JButton emsearch;
    private javax.swing.JTextField emstaff;
    private javax.swing.JTextField emsystem;
    private javax.swing.JButton emupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
